version: 1

before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy -go=1.21

builds:
  - env:
      - CGO_ENABLED=0
    binary: git-age
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - format: tar.gz
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        format: zip

sboms:
  - artifacts: binary

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

nfpms:
  - package_name: git-age
    homepage: https://github.com/prskr/git-age
    maintainer: Peter Kurfer <peter.kurfer@gmail.com>
    license: MIT
    formats:
      - apk
      - deb
      - rpm
    dependencies:
      - git

brews:
  - name: git-age
    homepage: https://github.com/prskr/git-age
    description: |-
      git-age is a smudge/clean filter to encrypt/decrypt files in a git repository transparently
    license: "MIT"
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com
    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"
    skip_upload: auto
    folder: deploy/homebrew
    dependencies:
      - name: git
        os: mac
    test: |
      system "#{bin}/git-age --help"
    repository:
      owner: prskr
      name: the-prancing-package
      token: "{{ .Env.GH_TAP_PAT }}"
      pull_request:
        enabled: true