site_name: git-age
site_url: https:// docs.git-age.icb4dc0.de
theme:
  name: material
  features:
    - navigation.instant
    - search.suggest
    - search.highlight
    - toc.integrate

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

plugins:
  - search
