name: Build documentation

on:
  push:
    branches: ["main"]

env:
  INSTANCE: 'web/g'
  ARTIFACT: 'webHelpHI2-all.zip'

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build docs using Writerside Docker builder
        uses: JetBrains/writerside-github-action@v4
        with:
          instance: ${{ env.INSTANCE }}
          artifact: ${{ env.ARTIFACT }}
          location: ./docs
