name: Go build
on:
  push:
    branches:
      - main
    tags:
      - "*"
  pull_request:
    branches:
      - main

permissions:
  checks: write
  contents: write
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: '0'
          fetch-tags: 'true'

      - name: Setup Go 1.21.x
        uses: actions/setup-go@v5
        with:
          # Semantic version range syntax or exact version of Go
          go-version: '1.21.x'

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3

      - name: Snapshot release
        uses: goreleaser/goreleaser-action@v5
        if: ${{ !startsWith(github.ref, 'refs/tags/v') }}
        with:
          distribution: goreleaser
          version: latest
          args: release --clean --snapshot

      - name: Release
        uses: goreleaser/goreleaser-action@v5
        if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}