name: Go build
on:
  push:
    tags:
      - "*"

permissions:
  checks: write
  contents: write
  packages: write
  pull-requests: write
  pages: write
  id-token: write

jobs:
  release:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: '0'
          fetch-tags: 'true'

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          # Semantic version range syntax or exact version of Go
          go-version: '1.21.x'

      - name: Setup Syft
        run: curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin

      - name: Install ronn
        run: sudo apt-get update && sudo apt-get install -y ronn

      - name: Install gotestsum
        run: go install gotest.tools/gotestsum@latest

      - name: Init go
        run: |
          go mod download
          go generate .

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3

      - name: Test
        run: |
          gotestsum --format pkgname -- -covermode=atomic ./...

      # run release only on linux
      - name: Release
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'docs/'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4